#ifndef MotionCalibrationCONSTRAINT_H_
#define MotionCalibration_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* MotionCalibrationCONSTRAINT_H_ */
