#include "Plans/GameStrategy/Gameplay/constraints/DefendPlay1457173681216Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1457173681216) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DefendPlay

/*		
 * Tasks: 
 * - EP:1457173750608 : Attack (1222613952469)
 * - EP:1457173768386 : Blocker (1432209050494)
 * - EP:1457173771067 : Defend (1225115406909)
 *
 * States:
 * - Attack (1457173750607)
 * - Block (1457173773492)
 * - Defend (1457173775213)
 *
 * Vars:
 */

// State: Attack

// State: Attack

// State: Block

// State: Block

// State: Defend

// State: Defend

}
