#include "Plans/GameStrategy/Gameplay/constraints/GamePlay1457173546734Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1457173546734) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:GamePlay

/*		
 * Tasks: 
 * - EP:1457173565463 : DefaultTask (1225112227903)
 * - EP:1457173833589 : KeepGoal (1221754402444)
 *
 * States:
 * - Defend (1457173565462)
 * - Attack (1457173576569)
 * - DefendGoal (1457173842758)
 *
 * Vars:
 */

// State: Defend

// State: Defend

// State: Attack

// State: Attack

// State: DefendGoal

// State: DefendGoal

}
