#include "Plans/Standards/Opponent/Penalty/constraints/OppInGamePenalty1466968232004Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1466968232004) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:OppInGamePenalty

    /*		
     * Tasks: 
     * - EP:1466968232006 : SupportAttack (1225115536468)
     * - EP:1466975602577 : Attack (1222613952469)
     * - EP:1466975645495 : Block (1461237765109)
     *
     * States:
     * - Pos4Rebounce (1466968232005)
     * - Pos4Intercept (1466975612430)
     * - Block (1466975637792)
     *
     * Vars:
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: []
     * Domain Variables:

     * forall agents in Block let v = [x, y] 

     */
    void Constraint1466975666362::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1466975666362) ENABLED START*/
        /*PROTECTED REGION END*/
    }

// State: Pos4Rebounce

// State: Pos4Rebounce

// State: Pos4Intercept

// State: Pos4Intercept

// State: Block

// State: Block

}
