#include "Plans/ActuatorTest/constraints/ActuatorTestMaster1417017436952Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1417017436952) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:ActuatorTestMaster

/*		
 * Tasks: 
 * - EP:1417017436954 : DefaultTask (1225112227903)
 *
 * States:
 * - Stop (1417017436953)
 * - DriveForwardAndActuate (1417017460581)
 * - Joystick (1435321198760)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: DriveForwardAndActuate

// State: DriveForwardAndActuate

// State: Joystick

// State: Joystick

}
