#!/usr/bin/env python
import sys

from rqt_gui.main import Main

import argparse

def add_arguments(parser):
    group = parser.add_argument_group('Options for rqt_msl_refbox plugin')
    group.add_argument('--hide-menu', '-m',
            help='Hide Refbox menu bar in plugin',
            action='store_true')
    group.add_argument('--display-config', '-d', metavar='FILE',
            type=argparse.FileType('r'),
            help='A display config file (.msl_refbox) to load')

main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_msl_refbox/Refbox', plugin_argument_provider=add_arguments))
