#ifndef LemniskateCONSTRAINT_H_
#define Lemniskate_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* LemniskateCONSTRAINT_H_ */
