#ifndef DriveInSquareCONSTRAINT_H_
#define DriveInSquare_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* DriveInSquareCONSTRAINT_H_ */
