#include "Plans/TestPlans/DribbleTestMBE/LemniskateAlignToNP1542642731136.h"
using namespace alica;
/*PROTECTED REGION ID(eph1542642731136) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:LemniskateAlignToNP

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1542642731168

     */
    shared_ptr<UtilityFunction> UtilityFunction1542642731136::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1542642731136) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: STOP in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): StopDefault, (PlanID): 1413992626194 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731149::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731148) ENABLED START*/
        return wm->game->checkSituation(msl::Situation::Start);
        /*PROTECTED REGION END*/

    }

    //State: start in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[0,0], (PlanID): 1542642784050 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731151::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731150) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P1 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[-1637,997], (PlanID): 1542643029370 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731153::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731152) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P2 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[-2828,0], (PlanID): 1542643155143 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731155::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731154) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P3 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[-1637,-997], (PlanID): 1542643305598 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731157::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731156) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P4 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[0,0], (PlanID): 1542642784050 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731159::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731158) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P5 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignToPoint[1637,997], (PlanID): 1542643508664 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731161::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731160) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P6 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[2828,0], (PlanID): 1542643768497 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731163::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731162) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P7 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[1637,-997], (PlanID): 1542643893844 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731165::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731164) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: P8 in Plan: LemniskateAlignToNP

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[0,0], (PlanID): 1542642784050 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1542642731168)
     *
     * States:
     *   - STOP (1542642731138)
     *   - start (1542642731139)
     *   - P1 (1542642731140)
     *   - P2 (1542642731141)
     *   - P3 (1542642731142)
     *   - P4 (1542642731143)
     *   - P5 (1542642731144)
     *   - P6 (1542642731145)
     *   - P7 (1542642731146)
     *   - P8 (1542642731147)
     *
     * Vars:
     */
    bool TransitionCondition1542642731167::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1542642731166) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

}
