#include "Plans/Standards/Own/KickOff/constraints/OwnKickOff1438785376159Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1438785376159) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:OwnKickOff

/*		
 * Tasks: 
 * - EP:1438785376161 : ExecuteStandard (1439997010902)
 * - EP:1438785392109 : ReceiveStandard (1439997023446)
 *
 * States:
 * - PosExec (1438785376160)
 * - PosRecv (1438785501838)
 * - GrabBall (1440675376134)
 * - Pass (1440772305591)
 * - Receive (1440772454611)
 * - Success (1440772500050)
 *
 * Vars:
 */

// State: PosExec

// State: PosExec

// State: PosRecv

// State: PosRecv

// State: GrabBall

// State: GrabBall

// State: Pass

// State: Pass

// State: Receive

// State: Receive

// State: Success

// State: Success

}
