#ifndef OwnStdSingleRobotCONSTRAINT_H_
#define OwnStdSingleRobot_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* OwnStdSingleRobotCONSTRAINT_H_ */
