#include "Plans/GameStrategy/OppStandards/constraints/GenericOppStandardExecuter1429109528736Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1429109528736) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:GenericOppStandardExecuter

/*		
 * Tasks: 
 * - EP:1429109572409 : Blocker (1429109227638)
 * - EP:1429109634871 : StandardDefend (1429111464037)
 * - EP:1429109772867 : Watcher (1429108494059)
 *
 * States:
 * - BlockerExecution (1429109572408)
 * - StandardDefendExecution (1429109804215)
 * - WatcherExecution (1429109805827)
 *
 * Vars:
 */

// State: BlockerExecution

// State: BlockerExecution

// State: StandardDefendExecution

// State: StandardDefendExecution

// State: WatcherExecution

// State: WatcherExecution

}
