#include "Plans/GameStrategy/OppStandards/constraints/OppStandards1426694865227Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1426694865227) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:OppStandards

/*		
 * Tasks: 
 * - EP:1426694865229 : DefaultTask (1225112227903)
 *
 * States:
 * - Dummy (1426694865228)
 * - FreeKick (1426697288024)
 * - GoalKick (1426697304719)
 * - KickOff (1426697310861)
 * - ThrowIn (1426697315032)
 * - Penalty (1426697322419)
 * - CornerKick (1426697332614)
 * - NewSuccessState (1426697367576)
 *
 * Vars:
 */

// State: Dummy

// State: Dummy

// State: FreeKick

// State: FreeKick

// State: GoalKick

// State: GoalKick

// State: KickOff

// State: KickOff

// State: ThrowIn

// State: ThrowIn

// State: Penalty

// State: Penalty

// State: CornerKick

// State: CornerKick

// State: NewSuccessState

// State: NewSuccessState

}
