#ifndef DefendPlayCONSTRAINT_H_
#define DefendPlay_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* DefendPlayCONSTRAINT_H_ */
