#ifndef GamePlayCONSTRAINT_H_
#define GamePlay_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* GamePlayCONSTRAINT_H_ */
