#include "Plans/TestPlans/DribbleTestMBE/constraints/LemniskateAlignToNP1542642731136Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1542642731136) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:LemniskateAlignToNP

/*		
 * Tasks: 
 * - EP:1542642731168 : DefaultTask (1225112227903)
 *
 * States:
 * - STOP (1542642731138)
 * - start (1542642731139)
 * - P1 (1542642731140)
 * - P2 (1542642731141)
 * - P3 (1542642731142)
 * - P4 (1542642731143)
 * - P5 (1542642731144)
 * - P6 (1542642731145)
 * - P7 (1542642731146)
 * - P8 (1542642731147)
 *
 * Vars:
 */

// State: STOP

// State: STOP

// State: start

// State: start

// State: P1

// State: P1

// State: P2

// State: P2

// State: P3

// State: P3

// State: P4

// State: P4

// State: P5

// State: P5

// State: P6

// State: P6

// State: P7

// State: P7

// State: P8

// State: P8

}
