#include "Plans/TestPlans/DribbleTestMBE/constraints/Lemniskate1541947378314Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1541947378314) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Lemniskate

/*		
 * Tasks: 
 * - EP:1541947378316 : DefaultTask (1225112227903)
 *
 * States:
 * - STOP (1541947378315)
 * - start (1541947933168)
 * - P1 (1542039866490)
 * - P2 (1542040456227)
 * - P3 (1542040458653)
 * - P4 (1542527802217)
 * - P5 (1542527959475)
 * - P6 (1542528046356)
 * - P7 (1542528086857)
 * - P8 (1542528142131)
 *
 * Vars:
 */

// State: STOP

// State: STOP

// State: start

// State: start

// State: P1

// State: P1

// State: P2

// State: P2

// State: P3

// State: P3

// State: P4

// State: P4

// State: P5

// State: P5

// State: P6

// State: P6

// State: P7

// State: P7

// State: P8

// State: P8

}
