#include "Plans/TestPlans/DribbleControlTest/constraints/TestDribble1498664114905Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1498664114905) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestDribble

/*		
 * Tasks: 
 * - EP:1498664138706 : DefaultTask (1225112227903)
 *
 * States:
 * - GetBall (1498664138705)
 * - Dribble (1498664172284)
 *
 * Vars:
 */

// State: GetBall

// State: GetBall

// State: Dribble

// State: Dribble

}
