#include "Plans/GameStrategy/Other/constraints/DroppedBall1426694906399Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1426694906399) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DroppedBall

/*		
 * Tasks: 
 * - EP:1426694906401 : DefaultTask (1225112227903)
 * - EP:1457689420982 : Keeper (1221754402444)
 *
 * States:
 * - DropBallType (1426694906400)
 * - NewSuccessState (1426696458333)
 * - Keeper (1457689449670)
 *
 * Vars:
 */

// State: DropBallType

// State: DropBallType

// State: NewSuccessState

// State: NewSuccessState

// State: Keeper

// State: Keeper

}
