#include "Plans/GameStrategy/Other/constraints/SimpleDropBall1426696586622Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1426696586622) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:SimpleDropBall

/*		
 * Tasks: 
 * - EP:1426696586624 : DefaultTask (1225112227903)
 * - EP:1455538209889 : KeepGoal (1221754402444)
 *
 * States:
 * - Positioning (1426696586623)
 * - Execution (1426696626634)
 * - NewSuccessState (1426696638228)
 * - DefendGoal (1455538265766)
 * - Wander (1458562124636)
 *
 * Vars:
 */

// State: Positioning

// State: Positioning

// State: Execution

// State: Execution

// State: NewSuccessState

// State: NewSuccessState

// State: DefendGoal

// State: DefendGoal

// State: Wander

// State: Wander

}
