#ifndef DribbleCONSTRAINT_H_
#define Dribble_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* DribbleCONSTRAINT_H_ */
