#include "Plans/Attack/TestPlans/constraints/AttackOppGoalPlan1437902649389Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1437902649389) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:AttackOppGoalPlan

/*		
 * Tasks: 
 * - EP:1437902649391 : DefaultTask (1225112227903)
 *
 * States:
 * - GetBall (1437902649390)
 * - DribbleToOppPenaltySpot (1437902693350)
 * - DribbleToOwnPenaltySpot (1437902704803)
 * - NewSuccessState (1437902754765)
 * - Shoot (1437902762624)
 * - GetBall (1437903060557)
 *
 * Vars:
 */

// State: GetBall

// State: GetBall

// State: DribbleToOppPenaltySpot

// State: DribbleToOppPenaltySpot

// State: DribbleToOwnPenaltySpot

// State: DribbleToOwnPenaltySpot

// State: NewSuccessState

// State: NewSuccessState

// State: Shoot

// State: Shoot

// State: GetBall

// State: GetBall

}
