#include "Plans/Attack/TestPlans/constraints/DribbleToPointPlan1436960829485Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1436960829485) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DribbleToPointPlan

/*		
 * Tasks: 
 * - EP:1436960854733 : DefaultTask (1225112227903)
 *
 * States:
 * - DribbleToOppPenaltySpot (1436960962060)
 *
 * Vars:
 */

// State: DribbleToOppPenaltySpot

// State: DribbleToOppPenaltySpot

}
