#include "Plans/TestPlans/constraints/Circle1517049779097Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1517049779097) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Circle

/*		
 * Tasks: 
 * - EP:1517050156899 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1517050156898)
 * - NewState (1517050290391)
 * - NewState (1517050320135)
 * - NewState (1517050323399)
 * - NewState (1517050336217)
 * - NewState (1517050341337)
 * - NewState (1517050344714)
 * - NewState (1517050350139)
 * - NewState (1517053316696)
 * - NewSuccessState (1517053319601)
 *
 * Vars:
 */

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewState

// State: NewSuccessState

// State: NewSuccessState

}
