#include "Plans/Calibration/RotationCalibrationStopWrapper1491404851815.h"
using namespace alica;
/*PROTECTED REGION ID(eph1491404851815) ENABLED START*/ //Add additional using directives here
#include <MSLWorldModel.h>
#include <Game.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:RotationCalibrationStopWrapper

    //Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) :  

    /* 
     * Available Vars:
     */
    bool RunTimeCondition1491404930441::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1491404930441) ENABLED START*/
        return wm->game->checkSituation(msl::Situation::Stop) == false;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1491404851817

     */
    shared_ptr<UtilityFunction> UtilityFunction1491404851815::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1491404851815) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: Run in Plan: RotationCalibrationStopWrapper

}
