#include "Plans/Attack/constraints/AttackSupportPlan1434046705214Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1434046705214) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:AttackSupportPlan

/*		
 * Tasks: 
 * - EP:1434046705217 : AttackSupport (1225115536468)
 *
 * States:
 * - NewState (1434046705216)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
