#include "Plans/Attack/constraints/AttackPlay1434045709191Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1434045709191) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:AttackPlay

/*		
 * Tasks: 
 * - EP:1434045709194 : Attack (1222613952469)
 * - EP:1434045719840 : AttackSupport (1225115536468)
 * - EP:1434045723977 : Defend (1225115406909)
 * - EP:1434045771503 : Keeper (1221754402444)
 *
 * States:
 * - Attack (1434045709193)
 * - AttackSupport (1434045868018)
 * - Defend (1434045870617)
 * - KeepGoal (1434045873728)
 *
 * Vars:
 */

// State: Attack

// State: Attack

// State: AttackSupport

// State: AttackSupport

// State: Defend

// State: Defend

// State: KeepGoal

// State: KeepGoal

}
