#include "Plans/Attack/constraints/Dribble1434049476066Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1434049476066) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Dribble

/*		
 * Tasks: 
 * - EP:1434049476068 : Attack (1222613952469)
 *
 * States:
 * - Dribble (1434049476067)
 * - AlignToGoal (1434050474119)
 * - AttackAgain (1434050502701)
 * - ProtectBall (1434050522682)
 * - TurnOneEighty (1434050541225)
 *
 * Vars:
 */

// State: Dribble

// State: Dribble

// State: AlignToGoal

// State: AlignToGoal

// State: AttackAgain

// State: AttackAgain

// State: ProtectBall

// State: ProtectBall

// State: TurnOneEighty

// State: TurnOneEighty

}
