#include "Plans/Attack/constraints/Duel1450178655416Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1450178655416) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:Duel

/*		
 * Tasks: 
 * - EP:1450178655418 : DefaultTask (1225112227903)
 * - EP:1454522099169 : DefaultTask (1225112227903)
 *
 * States:
 * - Wait (1454522133266)
 * - Duel (1458127402884)
 * - Success (1458131546373)
 *
 * Vars:
 */

// State: Wait

// State: Wait

// State: Duel

// State: Duel

// State: Success

// State: Success

}
