#include "Plans/Attack/constraints/FreeZonePassing1508950989519Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1508950989519) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
    //Plan:FreeZonePassing

    /*		
     * Tasks: 
     * - EP:1508950989521 : DefaultTask (1225112227903)
     *
     * States:
     * - Passing (1508950989520)
     *
     * Vars:				
     * - x (1508951697442) 				
     * - y (1508951702562) 
     */

    /*
     * RuntimeCondition - (Name): NewRuntimeCondition
     * (ConditionString): 
     * Static Variables: [x, y]
     * Domain Variables:

     */
    void Constraint1508951693560::getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(cc1508951693560) ENABLED START*/
        /*PROTECTED REGION END*/
    }

// State: Passing

// State: Passing

}
