#include "Plans/Attack/constraints/StandardAttack1434046634656Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1434046634656) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:StandardAttack

/*		
 * Tasks: 
 * - EP:1434046634658 : Attack (1222613952469)
 *
 * States:
 * - GetBall (1434046634657)
 * - Duel (1434048406725)
 * - HaveBall (1434048705508)
 * - LostBall (1434715893346)
 * - SideLineGetBall (1450175617600)
 * - AdvanceAfterPass (1450175887984)
 *
 * Vars:
 */

// State: GetBall

// State: GetBall

// State: Duel

// State: Duel

// State: HaveBall

// State: HaveBall

// State: LostBall

// State: LostBall

// State: SideLineGetBall

// State: SideLineGetBall

// State: AdvanceAfterPass

// State: AdvanceAfterPass

}
