#ifndef ActuatorTestMasterCONSTRAINT_H_
#define ActuatorTestMaster_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ActuatorTestMasterCONSTRAINT_H_ */
