#ifndef WayPointPlanCONSTRAINT_H_
#define WayPointPlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* WayPointPlanCONSTRAINT_H_ */
