RefereeBoxState state
uint8 lastCommand
GameStage gameStage
uint16 elapsedSeconds
uint8 goalsCyan
uint8 goalsMagenta


uint8 command_joystick = 255
uint8 start = 115
uint8 stop = 83
uint8 halt = 72
uint8 ready = 32
uint8 firstHalf = 49
uint8 halftime = 104
uint8 secondHalf = 50
uint8 endGame = 101
uint8 cancel = 120
uint8 park = 76
uint8 restart = 110
uint8 cornerMagenta = 99
uint8 cornerCyan = 67
uint8 kickoffMagenta = 107
uint8 kickoffCyan = 75
uint8 freekickMagenta = 102
uint8 freekickCyan = 70
uint8 goalkickMagenta = 103
uint8 goalkickCyan = 71
uint8 throwinMagenta = 116
uint8 throwinCyan = 84
uint8 penaltyMagenta = 112
uint8 penaltyCyan = 80
uint8 droppedBall = 78
uint8 dummy = 42
uint8 goalMagenta = 97
uint8 goalCyan = 65
uint8 subgoalMagenta = 100
uint8 subgoalCyan = 68
uint8 outForRepairMagenta = 111
uint8 outForRepairCyan = 79
uint8 inForRepairMagenta = 105
uint8 inForRepairCyan = 73
