#include "Plans/ActuatorTest/ActuatorTestMaster1417017436952.h"
using namespace alica;
/*PROTECTED REGION ID(eph1417017436952) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:ActuatorTestMaster

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1417017436954

     */
    shared_ptr<UtilityFunction> UtilityFunction1417017436952::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1417017436952) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Stop in Plan: ActuatorTestMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): StopDefault, (PlanID): 1413992626194 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1417017436954)
     *
     * States:
     *   - Stop (1417017436953)
     *   - DriveForwardAndActuate (1417017460581)
     *
     * Vars:
     */
    bool TransitionCondition1417017585255::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1417017583911) ENABLED START*/
        return true;
        /*PROTECTED REGION END*/

    }

//State: DriveForwardAndActuate in Plan: ActuatorTestMaster

}
