#ifndef OwnInGamePenaltyCONSTRAINT_H_
#define OwnInGamePenalty_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* OwnInGamePenaltyCONSTRAINT_H_ */
