#ifndef ActuatorPassTestCONSTRAINT_H_
#define ActuatorPassTest_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ActuatorPassTestCONSTRAINT_H_ */
