#ifndef TestDribblePlanCONSTRAINT_H_
#define TestDribblePlan_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TestDribblePlanCONSTRAINT_H_ */
