#!/bin/bash

WORKSPACES_PATH=~/nao/dev

WORKSPACE_SIM_NAME=nao-sim-ws
WORKSPACE_SIM_DIR="$WORKSPACES_PATH/$WORKSPACE_SIM_NAME"
WORKSPACE_SIM_SRC_DIR="$WORKSPACE_SIM_DIR/src"

WORKSPACE_REAL_NAME=nao-real-ws
WORKSPACE_REAL_DIR="$WORKSPACES_PATH/$WORKSPACE_REAL_NAME"
WORKSPACE_REAL_SRC_DIR="$WORKSPACE_REAL_DIR/src"

WORKSPACE_ROS_NAME=nao-ros-ws
WORKSPACE_ROS_DIR="$WORKSPACES_PATH/$WORKSPACE_ROS_NAME"
WORKSPACE_ROS_SRC_DIR="$WORKSPACE_ROS_DIR/src"




