#include "Plans/GameStrategy/OwnStandards/constraints/GenericOwnStandardPositioning1428507630593Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1428507630593) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:GenericOwnStandardPositioning

/*		
 * Tasks: 
 * - EP:1428507664503 : Receiver (1428507797481)
 * - EP:1428507727863 : Executer (1428507765874)
 * - EP:1428507808894 : StandardDefend (1225112227903)
 *
 * States:
 * - ReceiverPositioning (1428507664502)
 * - ExecuterPositioning (1428507881899)
 * - StandardDefendPositioning (1428507884379)
 *
 * Vars:
 */

// State: ReceiverPositioning

// State: ReceiverPositioning

// State: ExecuterPositioning

// State: ExecuterPositioning

// State: StandardDefendPositioning

// State: StandardDefendPositioning

}
