#include "Plans/Standards/Own/Test/constraints/LongPassBasement1513176006534Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1513176006534) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:LongPassBasement

/*		
 * Tasks: 
 * - EP:1513176006536 : ExecuteStandard (1439997010902)
 * - EP:1513176019047 : ReceiveStandard (1439997023446)
 *
 * States:
 * - AlignExec (1513176006535)
 * - AlignRec (1513176035432)
 * - GrabBall (1513176098858)
 * - Pass (1513176103139)
 * - Stop (1513176106132)
 * - Success (1513176112686)
 * - Receive (1513176169159)
 * - CatchPass (1513786312435)
 *
 * Vars:
 */

// State: AlignExec

// State: AlignExec

// State: AlignRec

// State: AlignRec

// State: GrabBall

// State: GrabBall

// State: Pass

// State: Pass

// State: Stop

// State: Stop

// State: Success

// State: Success

// State: Receive

// State: Receive

// State: CatchPass

// State: CatchPass

}
