#include "Plans/Standards/Own/Test/constraints/TestConfigurableActuate1518256475491Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1518256475491) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestConfigurableActuate

/*		
 * Tasks: 
 * - EP:1518256475493 : DefaultTask (1225112227903)
 * - EP:1518256719934 : DefaultTask (1225112227903)
 *
 * States:
 * - UseConfig (1518256475492)
 * - UseParam (1518256723974)
 * - UseParam (1518257009829)
 * - UseConfig (1518257013318)
 * - UseConfig (1518257028132)
 * - UseParam (1518257033220)
 *
 * Vars:
 */

// State: UseConfig

// State: UseConfig

// State: UseParam

// State: UseParam

// State: UseParam

// State: UseParam

// State: UseConfig

// State: UseConfig

// State: UseConfig

// State: UseConfig

// State: UseParam

// State: UseParam

}
