#include "Plans/Standards/Own/Test/constraints/TestActuateMaster1518256493210Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1518256493210) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestActuateMaster

/*		
 * Tasks: 
 * - EP:1518256493212 : DefaultTask (1225112227903)
 *
 * States:
 * - TestConfigActuate (1518256493211)
 *
 * Vars:
 */

// State: TestConfigActuate

// State: TestConfigActuate

}
