#include "Plans/Calibration/constraints/TestRotation1492620432380Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1492620432380) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestRotation

/*		
 * Tasks: 
 * - EP:1492620432383 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1492620432381)
 * - Stop (1492620463395)
 *
 * Vars:
 */

// State: NewState

// State: NewState

// State: Stop

// State: Stop

}
