#include "Plans/Calibration/constraints/WheelRadiusCalibration1507130066325Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1507130066325) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:WheelRadiusCalibration

/*		
 * Tasks: 
 * - EP:1507130066327 : DefaultTask (1225112227903)
 *
 * States:
 * - Start (1507130066326)
 * - Drive (1507130150009)
 * - MeasureAndConfigure (1507130223303)
 * - Finished (1507130989734)
 * - RestartMotion (1507131359921)
 *
 * Vars:
 */

// State: Start

// State: Start

// State: Drive

// State: Drive

// State: MeasureAndConfigure

// State: MeasureAndConfigure

// State: Finished

// State: Finished

// State: RestartMotion

// State: RestartMotion

}
