#include "Plans/Penalty/constraints/OwnPenalty1431525185678Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1431525185678) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:OwnPenalty

/*		
 * Tasks: 
 * - EP:1431525245110 : ExecuteStandard (1439997010902)
 * - EP:1431526909013 : DefaultTask (1225112227903)
 *
 * States:
 * - DriveToMiddle (1431525245109)
 * - GrabBall (1431526626723)
 * - AlignAndShoot (1431526769660)
 * - Stop (1431526917231)
 * - Success (1432744233327)
 * - WaitForStart (1433338496106)
 *
 * Vars:
 */

// State: DriveToMiddle

// State: DriveToMiddle

// State: GrabBall

// State: GrabBall

// State: AlignAndShoot

// State: AlignAndShoot

// State: Stop

// State: Stop

// State: Success

// State: Success

// State: WaitForStart

// State: WaitForStart

}
