#ifndef LongPassBasementCONSTRAINT_H_
#define LongPassBasement_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* LongPassBasementCONSTRAINT_H_ */
