#include "Plans/TestPlans/DribbleTestMOS/constraints/CircleCenter1518624635783Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1518624635783) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CircleCenter

/*		
 * Tasks: 
 * - EP:1518624635785 : DefaultTask (1225112227903)
 *
 * States:
 * - N (1518624635784)
 * - NO (1518624878623)
 * - NOO (1518624881576)
 * - O (1518624884409)
 * - SOO (1518624886995)
 * - SO (1518624889603)
 * - S (1518624892228)
 * - SW (1518624896101)
 * - SWW (1518624898694)
 * - W (1518624900831)
 * - NWW (1518624902640)
 * - NW (1518624906169)
 * - N2 (1518624910218)
 * - NewSuccessState (1518624915083)
 *
 * Vars:
 */

// State: N

// State: N

// State: NO

// State: NO

// State: NOO

// State: NOO

// State: O

// State: O

// State: SOO

// State: SOO

// State: SO

// State: SO

// State: S

// State: S

// State: SW

// State: SW

// State: SWW

// State: SWW

// State: W

// State: W

// State: NWW

// State: NWW

// State: NW

// State: NW

// State: N2

// State: N2

// State: NewSuccessState

// State: NewSuccessState

}
