#include "Plans/TestPlans/DribbleTestMOS/constraints/DriveStraightViewZigZag1518628181064Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1518628181064) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DriveStraightViewZigZag

/*		
 * Tasks: 
 * - EP:1518628208302 : DefaultTask (1225112227903)
 *
 * States:
 * - Zig1 (1518628208301)
 * - Zag1 (1518628264747)
 * - Zig2 (1518628271731)
 * - Zag2 (1518628274520)
 * - Zig3 (1518628283827)
 * - Zag3 (1518628286000)
 * - Zig4 (1518628290233)
 * - Zag4 (1518628292258)
 * - Zig5 (1518628303950)
 * - Zag5 (1518628307967)
 * - Zig6 (1518628314413)
 * - Zag6 (1518628321479)
 * - Turn (1518628712392)
 * - Zag7 (1518628752744)
 * - Zig7 (1518628756592)
 * - Zag8 (1518628760064)
 * - Zig8 (1518628764719)
 * - Zag9 (1518628767896)
 * - Zig9 (1518628771551)
 * - Zag10 (1518628774590)
 * - Zig10 (1518628777877)
 * - Zag11 (1518628780303)
 * - Zig11 (1518628783130)
 * - Zag12 (1518628785929)
 * - Zig12 (1518628789283)
 *
 * Vars:
 */

// State: Zig1

// State: Zig1

// State: Zag1

// State: Zag1

// State: Zig2

// State: Zig2

// State: Zag2

// State: Zag2

// State: Zig3

// State: Zig3

// State: Zag3

// State: Zag3

// State: Zig4

// State: Zig4

// State: Zag4

// State: Zag4

// State: Zig5

// State: Zig5

// State: Zag5

// State: Zag5

// State: Zig6

// State: Zig6

// State: Zag6

// State: Zag6

// State: Turn

// State: Turn

// State: Zag7

// State: Zag7

// State: Zig7

// State: Zig7

// State: Zag8

// State: Zag8

// State: Zig8

// State: Zig8

// State: Zag9

// State: Zag9

// State: Zig9

// State: Zig9

// State: Zag10

// State: Zag10

// State: Zig10

// State: Zig10

// State: Zag11

// State: Zag11

// State: Zig11

// State: Zig11

// State: Zag12

// State: Zag12

// State: Zig12

// State: Zig12

}
