#include "Plans/TestPlans/DribbleTestMOS/constraints/InitialForwardBackward1519032290449Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1519032290449) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:InitialForwardBackward

/*		
 * Tasks: 
 * - EP:1519032339542 : DefaultTask (1225112227903)
 *
 * States:
 * - ToRootPoint (1519032339541)
 * - WaitForBall (1519032827198)
 * - WaitShortly (1519032838047)
 * - Forward1 (1519033439526)
 * - WaitForBall2 (1519033689526)
 * - WaitShortly2 (1519033691856)
 * - Backward1 (1519033693855)
 * - ToRoot2 (1519033695455)
 * - ToRoot3 (1519033697834)
 * - WaitForBall3 (1519033700396)
 * - WaitShortly3 (1519033702534)
 * - Forward2 (1519033705513)
 * - ToRoot4 (1519033713182)
 * - WaitForBall4 (1519033715231)
 * - WaitShortly4 (1519033717576)
 * - Backward2 (1519033719721)
 * - ToRoot5 (1519033721755)
 * - WaitForBall5 (1519033724271)
 * - WaitShortly5 (1519033726450)
 * - Forward3 (1519033728667)
 * - ToRoot6 (1519033730767)
 * - WaitForBall6 (1519033733344)
 * - WaitShortly6 (1519033735835)
 * - Backward3 (1519033738336)
 * - finished (1519033778279)
 *
 * Vars:
 */

// State: ToRootPoint

// State: ToRootPoint

// State: WaitForBall

// State: WaitForBall

// State: WaitShortly

// State: WaitShortly

// State: Forward1

// State: Forward1

// State: WaitForBall2

// State: WaitForBall2

// State: WaitShortly2

// State: WaitShortly2

// State: Backward1

// State: Backward1

// State: ToRoot2

// State: ToRoot2

// State: ToRoot3

// State: ToRoot3

// State: WaitForBall3

// State: WaitForBall3

// State: WaitShortly3

// State: WaitShortly3

// State: Forward2

// State: Forward2

// State: ToRoot4

// State: ToRoot4

// State: WaitForBall4

// State: WaitForBall4

// State: WaitShortly4

// State: WaitShortly4

// State: Backward2

// State: Backward2

// State: ToRoot5

// State: ToRoot5

// State: WaitForBall5

// State: WaitForBall5

// State: WaitShortly5

// State: WaitShortly5

// State: Forward3

// State: Forward3

// State: ToRoot6

// State: ToRoot6

// State: WaitForBall6

// State: WaitForBall6

// State: WaitShortly6

// State: WaitShortly6

// State: Backward3

// State: Backward3

// State: finished

// State: finished

}
