set(_CATKIN_CURRENT_PACKAGE "msl_astra_pro_driver")
set(msl_astra_pro_driver_VERSION "0.0.0")
set(msl_astra_pro_driver_MAINTAINER "tobi <tobi@todo.todo>")
set(msl_astra_pro_driver_PACKAGE_FORMAT "1")
set(msl_astra_pro_driver_BUILD_DEPENDS "roslib" "roscpp" "rospack")
set(msl_astra_pro_driver_BUILD_EXPORT_DEPENDS "roslib" "rospack" "roscpp")
set(msl_astra_pro_driver_BUILDTOOL_DEPENDS "catkin")
set(msl_astra_pro_driver_BUILDTOOL_EXPORT_DEPENDS )
set(msl_astra_pro_driver_EXEC_DEPENDS "roslib" "rospack" "roscpp")
set(msl_astra_pro_driver_RUN_DEPENDS "roslib" "rospack" "roscpp")
set(msl_astra_pro_driver_TEST_DEPENDS )
set(msl_astra_pro_driver_DOC_DEPENDS )
set(msl_astra_pro_driver_DEPRECATED "")