#ifndef DriveZigZagViewZigZagCONSTRAINT_H_
#define DriveZigZagViewZigZag_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* DriveZigZagViewZigZagCONSTRAINT_H_ */
