#ifndef InitialForwardBackwardCONSTRAINT_H_
#define InitialForwardBackward_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* InitialForwardBackwardCONSTRAINT_H_ */
