#include "Plans/Standards/Own/KickOff/OwnKickOff1438785376159.h"
using namespace alica;
/*PROTECTED REGION ID(eph1438785376159) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:OwnKickOff

    /* generated comment
     
     Task: ExecuteStandard  -> EntryPoint-ID: 1438785376161

     Task: ReceiveStandard  -> EntryPoint-ID: 1438785392109

     */
    shared_ptr<UtilityFunction> UtilityFunction1438785376159::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1438785376159) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: PosExec in Plan: OwnKickOff

    /*
     *		
     * Transition:
     *   - Name: PosExec2GrabBall, ConditionString: , Comment : From PosExec 2 GrabBall State: If we reached the executor position. 
     *
     * Plans in State: 				
     *   - Plan - (Name): PositionExecutorDefault, (PlanID): 1438790487994 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1438785376161)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1438785392109)
     *
     * States:
     *   - PosExec (1438785376160)
     *   - PosRecv (1438785501838)
     *   - GrabBall (1440675376134)
     *
     * Vars:
     */
    bool TransitionCondition1440675385644::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1440675383814) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: PosRecv in Plan: OwnKickOff

//State: GrabBall in Plan: OwnKickOff

}
