#include "Plans/Attack/AttackSupportPlan1434046705214.h"
using namespace alica;
/*PROTECTED REGION ID(eph1434046705214) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:AttackSupportPlan

    /* generated comment
     
     Task: AttackSupport  -> EntryPoint-ID: 1434046705217

     */
    shared_ptr<UtilityFunction> UtilityFunction1434046705214::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1434046705214) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: AttackSupportPlan

}
