#include "Plans/Attack/Duel1450178655416.h"
using namespace alica;
/*PROTECTED REGION ID(eph1450178655416) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:Duel

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1450178655418

     Task: DefaultTask  -> EntryPoint-ID: 1454522099169

     */
    shared_ptr<UtilityFunction> UtilityFunction1450178655416::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1450178655416) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Wait in Plan: Duel

    //State: GetBallAggressively in Plan: Duel

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : haveBall 
     *
     * Plans in State: 				
     *   - Plan - (Name): GetBallDefault, (PlanID): 1414840399972 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1450178655418)
     *   - DefaultTask (1225112227903) (Entrypoint: 1454522099169)
     *
     * States:
     *   - Wait (1454522133266)
     *   - GetBallAggressively (1455731653038)
     *   - Duel (1455731683998)
     *
     * Vars:
     */
    bool TransitionCondition1455731695918::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1455731694960) ENABLED START*/
        return wm->ball.haveBall();
        /*PROTECTED REGION END*/

    }

//State: Duel in Plan: Duel

}
