#include "Plans/Attack/StandardKickOff1438777024734.h"
using namespace alica;
/*PROTECTED REGION ID(eph1438777024734) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:StandardKickOff

    /* generated comment
     
     Task: KickOffPassBall  -> EntryPoint-ID: 1438777024736

     */
    shared_ptr<UtilityFunction> UtilityFunction1438777024734::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1438777024734) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: StandardKickOff

}
