#include "Plans/Attack/Tackle1434116965565.h"
using namespace alica;
/*PROTECTED REGION ID(eph1434116965565) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:Tackle

    /* generated comment
     
     Task: Attack  -> EntryPoint-ID: 1434116965567

     */
    shared_ptr<UtilityFunction> UtilityFunction1434116965565::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1434116965565) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Tackle in Plan: Tackle

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : lostBall 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - Attack (1222613952469) (Entrypoint: 1434116965567)
     *
     * States:
     *   - Tackle (1434116965566)
     *   - GrabBall (1434117152274)
     *
     * Vars:
     */
    bool TransitionCondition1434117165674::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1434117164895) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: GrabBall in Plan: Tackle

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : haveBall 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - Attack (1222613952469) (Entrypoint: 1434116965567)
     *
     * States:
     *   - Tackle (1434116965566)
     *   - GrabBall (1434117152274)
     *
     * Vars:
     */
    bool TransitionCondition1434117164630::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1434117163845) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

}
