#include "Plans/GenericStandards/constraints/DummyMasterPlan1432139066765Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1432139066765) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DummyMasterPlan

/*		
 * Tasks: 
 * - EP:1432139066767 : Blocker (1225112227903)
 *
 * States:
 * - NewState (1432139066766)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
