#include "Plans/GenericStandards/constraints/GenericExecute1431522123418Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1431522123418) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:GenericExecute

/*		
 * Tasks: 
 * - EP:1431522155980 : Executor (1432208722106)
 * - EP:1431522269326 : Receiver (1432208722109)
 * - EP:1431523395534 : Blocker (1432208722113)
 * - EP:1431523422152 : Defender (1432208722116)
 *
 * States:
 * - GrabBall (1431522155979)
 * - Align (1431522297705)
 * - Pass (1431522763494)
 * - Receive (1431522912251)
 * - Success (1431522995646)
 * - Block (1431523482646)
 * - Defend (1431524014799)
 * - SpatialDefend (1431524769489)
 *
 * Vars:
 */

// State: GrabBall

// State: GrabBall

// State: Align

// State: Align

// State: Pass

// State: Pass

// State: Receive

// State: Receive

// State: Success

// State: Success

// State: Block

// State: Block

// State: Defend

// State: Defend

// State: SpatialDefend

// State: SpatialDefend

}
