#include "Plans/GenericStandards/constraints/GenericDefend1432133473779Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1432133473779) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:GenericDefend

/*		
 * Tasks: 
 * - EP:1432209644156 : Defend (1225115406909)
 * - EP:1432209646142 : Blocker (1432209050494)
 *
 * States:
 * - Block (1432133473780)
 * - Defend (1432134414694)
 * - Success (1432134598332)
 *
 * Vars:
 */

// State: Block

// State: Block

// State: Defend

// State: Defend

// State: Success

// State: Success

}
