#ifndef OwnFreeKickInOppHalfCONSTRAINT_H_
#define OwnFreeKickInOppHalf_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

    class Constraint1467206311808 : public BasicConstraint
    {
        void getConstraint(shared_ptr<ProblemDescriptor> c, shared_ptr<RunningPlan> rp);
    };

} /* namespace alica */

#endif /* OwnFreeKickInOppHalfCONSTRAINT_H_ */
