/*
 * DribbleForward.h
 *
 *  Created on: Dec 14, 2016
 *      Author: cn
 */

#ifndef AUTOGENERATED_SRC_PLANS_DRIBBLECALIBRATION_BEHAVIOURS_CALIBRATIONS_DRIBBLEFORWARD_H_
#define AUTOGENERATED_SRC_PLANS_DRIBBLECALIBRATION_BEHAVIOURS_CALIBRATIONS_DRIBBLEFORWARD_H_

#include "Plans/DribbleCalibration/Behaviours/Interfaces/ICalibration.h"
#include "Plans/DribbleCalibration/Container/MovementContainer.h"
#include "SystemConfig.h"

class DribbleForward : public ICalibration
{
public:
	DribbleForward();
	virtual ~DribbleForward();

	MotionControl move(int trans);
	void writeConfigParameters();
	void readConfigParameters();
	void adaptParams();
	void resetParams();

private:
	MovementContainer mCon;

	// parameters
	double velToInput;

	// calibration parameters
	double changingValue;
	double defaultValue;
};

#endif /* AUTOGENERATED_SRC_PLANS_DRIBBLECALIBRATION_BEHAVIOURS_CALIBRATIONS_DRIBBLEFORWARD_H_ */
