#include "Plans/TwoHoledWall/constraints/TwoHoledWallMaster1417621468963Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1417621468963) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TwoHoledWallMaster

/*		
 * Tasks: 
 * - EP:1417621468965 : DefaultTask (1225112227903)
 *
 * States:
 * - Stop (1417621468964)
 * - DriveToOrigin (1417621580835)
 * - Score (1417621589489)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: DriveToOrigin

// State: DriveToOrigin

// State: Score

// State: Score

}
