#!/bin/sh

interface=wlan0
logf=/var/log/keepwlan.log

while true
do
	if iwconfig $interface | grep -iq 'not-associated'
	then
		echo "[$(date)] Lost wifi connection, reconnecting..." >>$logf
		ifdown $interface
		ifup $interface
		sleep 5
	fi

	sleep 1
done
