#include "Plans/Example/constraints/DriverThaoSquare1450269525655Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1450269525655) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DriverThaoSquare

/*		
 * Tasks: 
 * - EP:1450269525657 : DefaultTask (1225112227903)
 *
 * States:
 * - Start (1450269525656)
 * - MoveSquare (1450269533144)
 *
 * Vars:
 */

// State: Start

// State: Start

// State: MoveSquare

// State: MoveSquare

}
