#include "Plans/Example/constraints/ThaoOwnpenalty1454506732570Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1454506732570) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:ThaoOwnpenalty

/*		
 * Tasks: 
 * - EP:1454506732572 : DefaultTask (1225112227903)
 *
 * States:
 * - DriveToMiddle (1454506732571)
 * - WaitForStart (1454507325367)
 * - GrabBall (1454507326785)
 * - AlignAndShoot (1454507336161)
 *
 * Vars:
 */

// State: DriveToMiddle

// State: DriveToMiddle

// State: WaitForStart

// State: WaitForStart

// State: GrabBall

// State: GrabBall

// State: AlignAndShoot

// State: AlignAndShoot

}
