#include "Plans/Standards/Opponent/constraints/OppStandardExecution1457015277573Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1457015277573) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:OppStandardExecution

/*		
 * Tasks: 
 * - EP:1457015277576 : DefaultTask (1225112227903)
 *
 * States:
 * - Position (1457015277575)
 * - WatchBall (1457015292860)
 * - NewSuccessState (1457015318562)
 *
 * Vars:
 */

// State: Position

// State: Position

// State: WatchBall

// State: WatchBall

// State: NewSuccessState

// State: NewSuccessState

}
