#include "Plans/Standards/Own/Test/TestConfigurableActuate1518256475491.h"
using namespace alica;
/*PROTECTED REGION ID(eph1518256475491) ENABLED START*/ //Add additional using directives here
#include <MSLWorldModel.h>
#include <Game.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TestConfigurableActuate

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1518256475493

     Task: DefaultTask  -> EntryPoint-ID: 1518256719934

     */
    shared_ptr<UtilityFunction> UtilityFunction1518256475491::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1518256475491) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: UseConfig in Plan: TestConfigurableActuate

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : 7 seconds till start 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardActuateDefault, (PlanID): 1435766278023 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256475493)
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256719934)
     *
     * States:
     *   - UseConfig (1518256475492)
     *   - UseParam (1518256723974)
     *   - UseParam (1518257009829)
     *   - UseConfig (1518257013318)
     *   - UseConfig (1518257028132)
     *   - UseParam (1518257033220)
     *
     * Vars:
     */
    bool TransitionCondition1518257026137::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1518257017363) ENABLED START*/
        return wm->getTime() - wm->game->getTimeSinceStart() > 7000000ul;
        /*PROTECTED REGION END*/

    }

    //State: UseParam in Plan: TestConfigurableActuate

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : 7 seconds till start 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardActuate2k, (PlanID): 1518257626027 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256475493)
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256719934)
     *
     * States:
     *   - UseConfig (1518256475492)
     *   - UseParam (1518256723974)
     *   - UseParam (1518257009829)
     *   - UseConfig (1518257013318)
     *   - UseConfig (1518257028132)
     *   - UseParam (1518257033220)
     *
     * Vars:
     */
    bool TransitionCondition1518257017227::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1518257015951) ENABLED START*/
        return wm->getTime() - wm->game->getTimeSinceStart() > 7000000000ul;
        /*PROTECTED REGION END*/

    }

    //State: UseParam in Plan: TestConfigurableActuate

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : 14 seconds till start 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardActuate2k, (PlanID): 1518257626027 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256475493)
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256719934)
     *
     * States:
     *   - UseConfig (1518256475492)
     *   - UseParam (1518256723974)
     *   - UseParam (1518257009829)
     *   - UseConfig (1518257013318)
     *   - UseConfig (1518257028132)
     *   - UseParam (1518257033220)
     *
     * Vars:
     */
    bool TransitionCondition1518257031921::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1518257030924) ENABLED START*/
        return wm->getTime() - wm->game->getTimeSinceStart() > 14000000000ul;
        /*PROTECTED REGION END*/

    }

    //State: UseConfig in Plan: TestConfigurableActuate

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : 14 seconds till start 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardActuateDefault, (PlanID): 1435766278023 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256475493)
     *   - DefaultTask (1225112227903) (Entrypoint: 1518256719934)
     *
     * States:
     *   - UseConfig (1518256475492)
     *   - UseParam (1518256723974)
     *   - UseParam (1518257009829)
     *   - UseConfig (1518257013318)
     *   - UseConfig (1518257028132)
     *   - UseParam (1518257033220)
     *
     * Vars:
     */
    bool TransitionCondition1518257036260::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1518257035564) ENABLED START*/
        return wm->game->getTimeSinceStart() > 14000000000ul;
        /*PROTECTED REGION END*/

    }

//State: UseConfig in Plan: TestConfigurableActuate

//State: UseParam in Plan: TestConfigurableActuate

}
