#include "Plans/GameStrategy/OwnStandards/GenericOwnStandardExecution1428508782222.h"
using namespace alica;
/*PROTECTED REGION ID(eph1428508782222) ENABLED START*/ //Add additional using directives here
#include "engine/Assignment.h"
#include "engine/AlicaEngine.h"
#include "engine/collections/StateCollection.h"
#include "engine/PlanRepository.h"
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:GenericOwnStandardExecution

    /* generated comment
     
     Task: Executer  -> EntryPoint-ID: 1428508810442

     Task: Receiver  -> EntryPoint-ID: 1428508819333

     Task: StandardDefend  -> EntryPoint-ID: 1428508821680

     */
    shared_ptr<UtilityFunction> UtilityFunction1428508782222::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1428508782222) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: ExecuterExecution in Plan: GenericOwnStandardExecution

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardAlignAndShootDefault, (PlanID): 1428509031167 
     *
     * Tasks: 
     *   - Executer (1428507765874) (Entrypoint: 1428508810442)
     *   - Receiver (1428507797481) (Entrypoint: 1428508819333)
     *   - StandardDefend (1429111464037) (Entrypoint: 1428508821680)
     *
     * States:
     *   - ExecuterExecution (1428508810441)
     *   - ReceiverExecution (1428508844911)
     *   - StandardDefendExecution (1428508847088)
     *   - NewSuccessState (1428509108972)
     *   - Block (1428509131566)
     *   - Receive (1428509271725)
     *
     * Vars:
     */
    bool TransitionCondition1428509248757::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1428509247624) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: ReceiverExecution in Plan: GenericOwnStandardExecution

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : one robot in state block:1428509131566 
     *
     * Plans in State: 				
     *   - Plan - (Name): StopDefault, (PlanID): 1413992626194 
     *
     * Tasks: 
     *   - Executer (1428507765874) (Entrypoint: 1428508810442)
     *   - Receiver (1428507797481) (Entrypoint: 1428508819333)
     *   - StandardDefend (1429111464037) (Entrypoint: 1428508821680)
     *
     * States:
     *   - ExecuterExecution (1428508810441)
     *   - ReceiverExecution (1428508844911)
     *   - StandardDefendExecution (1428508847088)
     *   - NewSuccessState (1428509108972)
     *   - Block (1428509131566)
     *   - Receive (1428509271725)
     *
     * Vars:
     */
    bool TransitionCondition1428509282512::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1428509280543) ENABLED START*/
        return rp->getAssignment()->getRobotStateMapping()->getRobotsInState(
                rp->getAlicaEngine()->getPlanRepository()->getStates()[1428509131566]).size() > 1;
        /*PROTECTED REGION END*/

    }

    //State: StandardDefendExecution in Plan: GenericOwnStandardExecution

    //State: NewSuccessState in Plan: GenericOwnStandardExecution

    //State: Block in Plan: GenericOwnStandardExecution

    //State: Receive in Plan: GenericOwnStandardExecution

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardReceiveDefault, (PlanID): 1428509534191 
     *
     * Tasks: 
     *   - Executer (1428507765874) (Entrypoint: 1428508810442)
     *   - Receiver (1428507797481) (Entrypoint: 1428508819333)
     *   - StandardDefend (1429111464037) (Entrypoint: 1428508821680)
     *
     * States:
     *   - ExecuterExecution (1428508810441)
     *   - ReceiverExecution (1428508844911)
     *   - StandardDefendExecution (1428508847088)
     *   - NewSuccessState (1428509108972)
     *   - Block (1428509131566)
     *   - Receive (1428509271725)
     *
     * Vars:
     */
    bool TransitionCondition1428509288287::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1428509286818) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

}
