#include "Plans/GameStrategy/OwnStandards/OwnStandards1426694875113.h"
using namespace alica;
/*PROTECTED REGION ID(eph1426694875113) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:OwnStandards

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1426694875115

     */
    shared_ptr<UtilityFunction> UtilityFunction1426694875113::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1426694875113) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Dummy in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation == CornerKick 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696897969::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696896987) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation == FreeKick 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696899156::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696898114) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation == GoalKick 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696900390::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696899284) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation == ThrowIn 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696901894::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696900543) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation == Penalty 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696903119::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696902014) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation == KickOff 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696904473::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696903255) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: FreeKick in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): OwnFreeKickType, (PlanID): 1426698015369 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696956076::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696954517) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: GoalKick in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): OwnGoalKickType, (PlanID): 1426698043458 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696957736::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696956228) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: Penalty in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): OwnPenaltyType, (PlanID): 1426698098722 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696959204::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696957920) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: ThrowIn in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): OwnThrowInType, (PlanID): 1426698121099 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696963628::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696961286) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: CornerKick in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): OwnCornerKickType, (PlanID): 1426697882552 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696954307::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696952905) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: KickOff in Plan: OwnStandards

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anyChildSuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): OwnKickOffType, (PlanID): 1426698076341 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426694875115)
     *
     * States:
     *   - Dummy (1426694875114)
     *   - FreeKick (1426696810907)
     *   - GoalKick (1426696817258)
     *   - Penalty (1426696823465)
     *   - ThrowIn (1426696855134)
     *   - CornerKick (1426696862884)
     *   - KickOff (1426696872622)
     *   - NewSuccessState (1426696949478)
     *
     * Vars:
     */
    bool TransitionCondition1426696961046::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696959405) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

//State: NewSuccessState in Plan: OwnStandards

}
