#include "ConditionCreator.h"

#include  "Plans/GameStrategy/OppStandards/OppStandards1426694865227.h"

#include  "Plans/GameStrategy/Other/Parking1426695119330.h"

#include  "Plans/GameStrategy/Other/SimpleDropBall1426696586622.h"

#include  "Plans/WM161413992564408.h"

#include  "Plans/GameStrategy/OppStandards/GenericOppStandard1426697871183.h"

#include  "Plans/GameStrategy/OwnStandards/GenericOwnStandard1426697860439.h"

#include  "Plans/TwoHoledWall/TwoHoledWallMaster1417621468963.h"

#include  "Plans/ActuatorTest/ActuatorTestMaster1417017436952.h"

#include  "Plans/GameStrategy/Gameplay/Gameplay1426694853089.h"

#include  "Plans/GameStrategy/Other/DroppedBall1426694906399.h"

#include  "Plans/GameStrategy/OwnStandards/OwnStandards1426694875113.h"

#include  "Plans/TwoHoledWall/ShootTwoHoledWall1417620189234.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1426697381689:

                return make_shared<TransitionCondition1426697381689>();

                break;

            case 1426697382983:

                return make_shared<TransitionCondition1426697382983>();

                break;

            case 1426697384088:

                return make_shared<TransitionCondition1426697384088>();

                break;

            case 1426697385319:

                return make_shared<TransitionCondition1426697385319>();

                break;

            case 1426697386739:

                return make_shared<TransitionCondition1426697386739>();

                break;

            case 1426697388059:

                return make_shared<TransitionCondition1426697388059>();

                break;

            case 1426697390236:

                return make_shared<TransitionCondition1426697390236>();

                break;

            case 1426697394359:

                return make_shared<TransitionCondition1426697394359>();

                break;

            case 1426697396107:

                return make_shared<TransitionCondition1426697396107>();

                break;

            case 1426697399106:

                return make_shared<TransitionCondition1426697399106>();

                break;

            case 1426697400936:

                return make_shared<TransitionCondition1426697400936>();

                break;

            case 1426697403188:

                return make_shared<TransitionCondition1426697403188>();

                break;

            case 1426696641527:

                return make_shared<TransitionCondition1426696641527>();

                break;

            case 1426696642635:

                return make_shared<TransitionCondition1426696642635>();

                break;

            case 1426691976695:

                return make_shared<TransitionCondition1426691976695>();

                break;

            case 1426691979272:

                return make_shared<TransitionCondition1426691979272>();

                break;

            case 1426691980585:

                return make_shared<TransitionCondition1426691980585>();

                break;

            case 1426692078983:

                return make_shared<TransitionCondition1426692078983>();

                break;

            case 1426692165988:

                return make_shared<TransitionCondition1426692165988>();

                break;

            case 1426692246279:

                return make_shared<TransitionCondition1426692246279>();

                break;

            case 1426692307991:

                return make_shared<TransitionCondition1426692307991>();

                break;

            case 1426692309848:

                return make_shared<TransitionCondition1426692309848>();

                break;

            case 1426692322491:

                return make_shared<TransitionCondition1426692322491>();

                break;

            case 1426692324569:

                return make_shared<TransitionCondition1426692324569>();

                break;

            case 1426692326693:

                return make_shared<TransitionCondition1426692326693>();

                break;

            case 1426692328653:

                return make_shared<TransitionCondition1426692328653>();

                break;

            case 1426692330833:

                return make_shared<TransitionCondition1426692330833>();

                break;

            case 1426692332679:

                return make_shared<TransitionCondition1426692332679>();

                break;

            case 1426692655810:

                return make_shared<TransitionCondition1426692655810>();

                break;

            case 1426698469169:

                return make_shared<TransitionCondition1426698469169>();

                break;

            case 1426698473926:

                return make_shared<TransitionCondition1426698473926>();

                break;

            case 1426698518818:

                return make_shared<TransitionCondition1426698518818>();

                break;

            case 1426698520600:

                return make_shared<TransitionCondition1426698520600>();

                break;

            case 1417621600501:

                return make_shared<TransitionCondition1417621600501>();

                break;

            case 1417621604870:

                return make_shared<TransitionCondition1417621604870>();

                break;

            case 1417621607305:

                return make_shared<TransitionCondition1417621607305>();

                break;

            case 1417621611163:

                return make_shared<TransitionCondition1417621611163>();

                break;

            case 1422464818034:

                return make_shared<TransitionCondition1422464818034>();

                break;

            case 1422464821945:

                return make_shared<TransitionCondition1422464821945>();

                break;

            case 1422464825529:

                return make_shared<TransitionCondition1422464825529>();

                break;

            case 1422464875980:

                return make_shared<TransitionCondition1422464875980>();

                break;

            case 1417017585255:

                return make_shared<TransitionCondition1417017585255>();

                break;

            case 1426696478377:

                return make_shared<TransitionCondition1426696478377>();

                break;

            case 1426696897969:

                return make_shared<TransitionCondition1426696897969>();

                break;

            case 1426696899156:

                return make_shared<TransitionCondition1426696899156>();

                break;

            case 1426696900390:

                return make_shared<TransitionCondition1426696900390>();

                break;

            case 1426696901894:

                return make_shared<TransitionCondition1426696901894>();

                break;

            case 1426696903119:

                return make_shared<TransitionCondition1426696903119>();

                break;

            case 1426696904473:

                return make_shared<TransitionCondition1426696904473>();

                break;

            case 1426696954307:

                return make_shared<TransitionCondition1426696954307>();

                break;

            case 1426696956076:

                return make_shared<TransitionCondition1426696956076>();

                break;

            case 1426696957736:

                return make_shared<TransitionCondition1426696957736>();

                break;

            case 1426696959204:

                return make_shared<TransitionCondition1426696959204>();

                break;

            case 1426696961046:

                return make_shared<TransitionCondition1426696961046>();

                break;

            case 1426696963628:

                return make_shared<TransitionCondition1426696963628>();

                break;

            case 1417620269159:

                return make_shared<TransitionCondition1417620269159>();

                break;

            case 1417620286821:

                return make_shared<TransitionCondition1417620286821>();

                break;

            case 1417620329181:

                return make_shared<TransitionCondition1417620329181>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
