#ifndef GenericOwnStandardPositioningCONSTRAINT_H_
#define GenericOwnStandardPositioning_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* GenericOwnStandardPositioningCONSTRAINT_H_ */
