#ifndef OwnStandardsCONSTRAINT_H_
#define OwnStandards_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* OwnStandardsCONSTRAINT_H_ */
