#ifndef OppFreeKickCONSTRAINT_H_
#define OppFreeKick_H_
#include "engine/BasicConstraint.h"
#include "MSLWorldModel.h"
#include "Rules.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

    class Constraint1445442215438 : public BasicConstraint
    {
        void getConstraint(shared_ptr<ConstraintDescriptor> c, shared_ptr<RunningPlan>);
        msl::MSLWorldModel* wm = msl::MSLWorldModel::get();
        msl::Rules rules;

    };

} /* namespace alica */

#endif /* OppFreeKickCONSTRAINT_H_ */
