#include "Plans/TestPlans/DribbleTestMOS/DriveAndTurnToOppositeSite1521283132783.h"
using namespace alica;
/*PROTECTED REGION ID(eph1521283132783) ENABLED START*/ //Add additional using directives here
#include <Ball.h>
#include <MSLWorldModel.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:DriveAndTurnToOppositeSite

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1521283132785

     */
    shared_ptr<UtilityFunction> UtilityFunction1521283132783::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1521283132783) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: InitialPos in Plan: DriveAndTurnToOppositeSite

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[-4000,0,4000,0,250], (PlanID): 1521281255214 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1521283132785)
     *
     * States:
     *   - InitialPos (1521283132784)
     *   - WaitShortly (1521283171226)
     *   - DriveToSite (1521283172827)
     *   - WaitForBall (1521283174412)
     *   - NewSuccessState (1521283242241)
     *
     * Vars:
     */
    bool TransitionCondition1521283236610::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1521283235652) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: WaitShortly in Plan: DriveAndTurnToOppositeSite

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1521283132785)
     *
     * States:
     *   - InitialPos (1521283132784)
     *   - WaitShortly (1521283171226)
     *   - DriveToSite (1521283172827)
     *   - WaitForBall (1521283174412)
     *   - NewSuccessState (1521283242241)
     *
     * Vars:
     */
    bool TransitionCondition1521283239559::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1521283238079) ENABLED START*/
        return this->isTimeOut(1000000000, rp->getStateStartTime(), rp);
        /*PROTECTED REGION END*/

    }

    //State: DriveToSite in Plan: DriveAndTurnToOppositeSite

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 				
     *   - Plan - (Name): DriveAndAlignTo[4000,0,-4100,0,250], (PlanID): 1521283343854 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1521283132785)
     *
     * States:
     *   - InitialPos (1521283132784)
     *   - WaitShortly (1521283171226)
     *   - DriveToSite (1521283172827)
     *   - WaitForBall (1521283174412)
     *   - NewSuccessState (1521283242241)
     *
     * Vars:
     */
    bool TransitionCondition1521283249550::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1521283248282) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: WaitForBall in Plan: DriveAndTurnToOppositeSite

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment :  
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1521283132785)
     *
     * States:
     *   - InitialPos (1521283132784)
     *   - WaitShortly (1521283171226)
     *   - DriveToSite (1521283172827)
     *   - WaitForBall (1521283174412)
     *   - NewSuccessState (1521283242241)
     *
     * Vars:
     */
    bool TransitionCondition1521283237926::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1521283236778) ENABLED START*/
        return wm->ball->haveBall();
        /*PROTECTED REGION END*/

    }

//State: NewSuccessState in Plan: DriveAndTurnToOppositeSite

}
