#include "Plans/Standards/Own/FreeKick/FreekickOwnHalf1464779892293.h"
using namespace alica;
/*PROTECTED REGION ID(eph1464779892293) ENABLED START*/ //Add additional using directives here
#include "BallXIntervall.h"
#include <MSLWorldModel.h>
#include <MSLFootballField.h>
#include <Game.h>
#include <Ball.h>
#include <WhiteBoard.h>
#include <Rules.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:FreekickOwnHalf

    //Check of RuntimeCondition - (Name): NewRuntimeCondition, (ConditionString): , (Comment) :  

    /* 
     * Available Vars:
     */
    bool RunTimeCondition1464780785574::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464780785574) ENABLED START*/
        return true;
        /*PROTECTED REGION END*/
    }

    /* generated comment
     
     Task: ExecuteStandard  -> EntryPoint-ID: 1464779892295

     Task: ReceiveStandard  -> EntryPoint-ID: 1464780621150

     Task: AlternativeReceive  -> EntryPoint-ID: 1464780622782

     Task: Block  -> EntryPoint-ID: 1464780624383

     */
    shared_ptr<UtilityFunction> UtilityFunction1464779892293::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1464779892293) ENABLED START*/

        vector<long> entryPoints;

        entryPoints.push_back(1464779892295); // ExecuteStandard
        entryPoints.push_back(1464780621150); // ReceiveStandard
        entryPoints.push_back(1464780624383); // Block
        entryPoints.push_back(1464780622782); // AlternitveReceive

        double angle = 55 * M_PI / 180; // nice angle to shoot on the goal
        BallXIntervall* us = new BallXIntervall(3.0, "FreekickOwnHalf", 3, entryPoints,
                                                -(msl::MSLWorldModel::get()->field->getFieldLength() / 2), 4800.0,
                                                1000.0);
        list<USummand*> utilSummands;
        utilSummands.push_back(us);
        shared_ptr < UtilityFunction > function = make_shared < UtilityFunction
                > ("FreeKickNearGoalTest", utilSummands, 0.1, 0.2, plan);
        return function;

        /*PROTECTED REGION END*/
    }

    //State: AlginExec in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : (child success && start) || (start && timeSinceStart > timeUntilEmergencyExecute) 
     *
     * Plans in State: 				
     *   - Plan - (Name): StandardActuateDefault, (PlanID): 1435766278023 				
     *   - Plan - (Name): ShovelSelectLowKick, (PlanID): 1435156714286 				
     *   - Plan - (Name): StandardAlignToPoint2ReceiversDefault, (PlanID): 1467229016494 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781041779::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781040324) ENABLED START*/
        return (rp->anyChildrenStatus(PlanStatus::Success) && wm->game->checkSituation(msl::Situation::Start))
                || (wm->game->checkSituation(msl::Situation::Start)
                        && (this->isTimeOut(this->timeUntilEmergencyExecute, wm->game->getTimeSinceStart(), rp)));
        /*PROTECTED REGION END*/

    }

    //State: AlginRec in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : pm for own id 
     *
     * Plans in State: 				
     *   - Plan - (Name): ReceiveInOppHalfDefault, (PlanID): 1462370388995 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781427853::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781426314) ENABLED START*/
        auto pm = wm->whiteBoard->getPassMsg();
        if (pm != nullptr && pm->senderID != wm->getOwnId() && pm->receiverID == wm->getOwnId())
        {
            return true;
        }
        return false;
        /*PROTECTED REGION END*/

    }

    //State: AlignAlternativeRec in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : pm for own id alternative 
     *
     * Plans in State: 				
     *   - Plan - (Name): PositionAlternativeReceiverDefault, (PlanID): 1462978671719 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781583659::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781582341) ENABLED START*/
        auto pm = wm->whiteBoard->getPassMsg();
        if (pm != nullptr && pm->senderID != wm->getOwnId() && pm->receiverID == wm->getOwnId())
        {
            return true;
        }
        return false;
        /*PROTECTED REGION END*/

    }

    //State: Block in Plan: FreekickOwnHalf

    //State: GrabBall in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : haveball 
     *
     * Plans in State: 				
     *   - Plan - (Name): ShovelSelectLowKick, (PlanID): 1435156714286 				
     *   - Plan - (Name): StandardActuateDefault, (PlanID): 1435766278023 				
     *   - Plan - (Name): StandardAlignAndGrab2ReceiversTIOH, (PlanID): 1462368748899 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781044511::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781042853) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: Pass in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : executed 
     *
     * Plans in State: 				
     *   - Plan - (Name): ShovelSelectLowKick, (PlanID): 1435156714286 				
     *   - Plan - (Name): ThrowInPassDefault, (PlanID): 1462363309950 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781045433::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781044679) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : lostball 
     *
     * Plans in State: 				
     *   - Plan - (Name): ShovelSelectLowKick, (PlanID): 1435156714286 				
     *   - Plan - (Name): ThrowInPassDefault, (PlanID): 1462363309950 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781329800::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781328367) ENABLED START*/
        return !wm->ball->haveBall();
        /*PROTECTED REGION END*/

    }

    //State: Wait in Plan: FreekickOwnHalf

    //State: Receive in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : pass received  
     *
     * Plans in State: 				
     *   - Plan - (Name): InterceptCarefullyDefault, (PlanID): 1427703234654 				
     *   - Plan - (Name): ShovelSelectHighKick, (PlanID): 1435156811453 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781495801::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781494047) ENABLED START*/
        return this->isTimeOut(this->rules->getStandbyTime() * 0.75, rp->getStateStartTime(), rp)
                || wm->ball->haveBall();
        /*PROTECTED REGION END*/

    }

    //State: Success in Plan: FreekickOwnHalf

    //State: ReceiveAlternative in Plan: FreekickOwnHalf

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : pass received from alternative 
     *
     * Plans in State: 				
     *   - Plan - (Name): InterceptCarefullyDefault, (PlanID): 1427703234654 
     *
     * Tasks: 
     *   - ExecuteStandard (1439997010902) (Entrypoint: 1464779892295)
     *   - ReceiveStandard (1439997023446) (Entrypoint: 1464780621150)
     *   - AlternativeReceive (1462360858945) (Entrypoint: 1464780622782)
     *   - Block (1461237765109) (Entrypoint: 1464780624383)
     *
     * States:
     *   - AlginExec (1464779892294)
     *   - AlginRec (1464780728003)
     *   - AlignAlternativeRec (1464780736932)
     *   - Block (1464780761597)
     *   - GrabBall (1464780991973)
     *   - Pass (1464780997998)
     *   - Wait (1464781012255)
     *   - Receive (1464781391707)
     *   - Success (1464781475476)
     *   - ReceiveAlternative (1464781530341)
     *   - SuccessAlternative (1464781564174)
     *
     * Vars:
     */
    bool TransitionCondition1464781589367::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1464781583908) ENABLED START*/
        return this->isTimeOut(this->rules->getStandbyTime() * 0.75, rp->getStateStartTime(), rp)
                || wm->ball->haveBall();
        /*PROTECTED REGION END*/

    }

//State: SuccessAlternative in Plan: FreekickOwnHalf

}
