#include "Plans/Defence/constraints/MidfieldDefense1458033329973Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1458033329973) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:MidfieldDefense

/*		
 * Tasks: 
 * - EP:1458033358326 : DefaultTask (1225112227903)
 *
 * States:
 * - MidFieldBlock (1458033358325)
 * - ReleaseMid (1458033385978)
 * - ReleaseOwnHalf (1458033395158)
 *
 * Vars:
 */

// State: MidFieldBlock

// State: MidFieldBlock

// State: ReleaseMid

// State: ReleaseMid

// State: ReleaseOwnHalf

// State: ReleaseOwnHalf

}
