#ifndef PointToPointCONSTRAINT_H_
#define PointToPoint_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* PointToPointCONSTRAINT_H_ */
