#include "Plans/Defence/Test/constraints/TestApproachBallMaster1430324312981Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1430324312981) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestApproachBallMaster

/*		
 * Tasks: 
 * - EP:1430324312983 : DefaultTask (1225112227903)
 *
 * States:
 * - Stop (1430324312982)
 * - AttackOpp (1430324405240)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: AttackOpp

// State: AttackOpp

}
