#include "Plans/Defence/Test/constraints/TestBackroomDefence1455127495970Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1455127495970) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestBackroomDefence

/*		
 * Tasks: 
 * - EP:1455127495972 : DefaultTask (1225112227903)
 *
 * States:
 * - Stop (1455127495971)
 * - BackroomDefence (1455127584801)
 *
 * Vars:
 */

// State: Stop

// State: Stop

// State: BackroomDefence

// State: BackroomDefence

}
