#ifndef GenericExecuteCONSTRAINT_H_
#define GenericExecute_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* GenericExecuteCONSTRAINT_H_ */
