#include "Plans/TestPlans/DriveInSquare/constraints/DriveInSquare1472044587219Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1472044587219) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DriveInSquare

/*		
 * Tasks: 
 * - EP:1472044615069 : DefaultTask (1225112227903)
 *
 * States:
 * - DriveUp (1472044615068)
 * - DriveLeft (1472044627757)
 * - DriveDown (1472044629029)
 * - DriveRight (1472044630706)
 *
 * Vars:
 */

// State: DriveUp

// State: DriveUp

// State: DriveLeft

// State: DriveLeft

// State: DriveDown

// State: DriveDown

// State: DriveRight

// State: DriveRight

}
