#include "Plans/TestPlans/DribbleControlTest/TestDribbleAroundTheBall1498663554104.h"
using namespace alica;
/*PROTECTED REGION ID(eph1498663554104) ENABLED START*/ //Add additional using directives here
#include "Game.h"
#include "MSLWorldModel.h"
#include "MSLEnums.h"
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TestDribbleAroundTheBall

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1498663554106

     */
    shared_ptr<UtilityFunction> UtilityFunction1498663554104::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1498663554104) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Stop in Plan: TestDribbleAroundTheBall

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Start 
     *
     * Plans in State: 				
     *   - Plan - (Name): StopDefault, (PlanID): 1413992626194 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1498663554106)
     *
     * States:
     *   - Stop (1498663554105)
     *   - Dribble (1498663949107)
     *
     * Vars:
     */
    bool TransitionCondition1498664087062::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1498664085559) ENABLED START*/
        return wm->game->checkSituation(msl::Situation::Start);
        /*PROTECTED REGION END*/

    }

    //State: Dribble in Plan: TestDribbleAroundTheBall

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Stop 
     *
     * Plans in State: 				
     *   - Plan - (Name): TestDribble, (PlanID): 1498664114905 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1498663554106)
     *
     * States:
     *   - Stop (1498663554105)
     *   - Dribble (1498663949107)
     *
     * Vars:
     */
    bool TransitionCondition1498664100103::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1498664098783) ENABLED START*/
    	return wm->game->checkSituation(msl::Situation::Stop);
        /*PROTECTED REGION END*/

    }

}
