#include "Plans/TestPlans/MotorControlTest/PointToPoint1489068076224.h"
using namespace alica;
/*PROTECTED REGION ID(eph1489068076224) ENABLED START*/ //Add additional using directives here
#include "MSLWorldModel.h"
#include "Game.h"
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:PointToPoint

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1489068076226

     */
    shared_ptr<UtilityFunction> UtilityFunction1489068076224::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1489068076224) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Stop in Plan: PointToPoint

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : start signal 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1489068076226)
     *
     * States:
     *   - Stop (1489068076225)
     *   - Drive (1489068089407)
     *
     * Vars:
     */
    bool TransitionCondition1489068108429::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1489068107311) ENABLED START*/
        return wm->game->checkSituation(msl::Situation::Start);
        /*PROTECTED REGION END*/

    }

    //State: Drive in Plan: PointToPoint

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : stop signal 
     *
     * Plans in State: 				
     *   - Plan - (Name): PointToPointDefault, (PlanID): 1489068194261 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1489068076226)
     *
     * States:
     *   - Stop (1489068076225)
     *   - Drive (1489068089407)
     *
     * Vars:
     */
    bool TransitionCondition1489068110424::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1489068108605) ENABLED START*/
        return wm->game->checkSituation(msl::Situation::Stop);
        /*PROTECTED REGION END*/

    }

}
