#!/bin/bash
set -e

if [ "$(id -u)" != "0" ]; then
   echo "no permissions: use sudo!" 1>&2
   exit 1
fi

hostfile="$HOME/cnws/src/cnc-msl/configuration/hosts"
robotip="$(grep $(hostname) $hostfile | tail -1 | cut -f 1 | tr -d ' ')"

interface="wlp5s0"
change_interfaces()
{
	configpath="$HOME/cnws/src/cnc-msl/configuration/"
	filename="${configpath}${1}"
	echo "'$robotip'"
	rm -f /etc/network/interfaces.d/*
	sed "s/ROBOT_ADDRESS/$robotip/g" $filename>/etc/network/interfaces.d/conf.interface
	ifdown "$interface" || echo "$interface already down"
	sleep 1
	ifup "$interface"
}

add_source()
{
	echo "Adding 'source /etc/network/interfaces.d/*' ..."
	echo 'source /etc/network/interfaces.d/*' >>/etc/network/interfaces
}

grep -q 'source /etc/network/interfaces.d/*' /etc/network/interfaces || add_source

option="$1"

case "${option}" in
field)
	echo  "Chaning to field"
	change_interfaces field.interface
		;;
git)
	echo  "Chaning to git"
	change_interfaces git.interface
		;; *)
		echo "usage: ${0} [field|git]"
esac
