#include "Plans/Standards/Own/Penalty/AfterGame/PenaltyMaster1466973051873.h"
using namespace alica;
/*PROTECTED REGION ID(eph1466973051873) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:PenaltyMaster

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1466973051875

     */
    shared_ptr<UtilityFunction> UtilityFunction1466973051873::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1466973051873) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Stop in Plan: PenaltyMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : situation = penalty 
     *
     * Plans in State: 				
     *   - Plan - (Name): StopDefault, (PlanID): 1413992626194 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1466973051875)
     *
     * States:
     *   - Stop (1466973051874)
     *   - Penalty (1466973070716)
     *
     * Vars:
     */
    bool TransitionCondition1466973077506::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1466973076640) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

    //State: Penalty in Plan: PenaltyMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : situation = stop 
     *
     * Plans in State: 				
     *   - Plan - (Name): AfterGamePenalty, (PlanID): 1466934340668 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1466973051875)
     *
     * States:
     *   - Stop (1466973051874)
     *   - Penalty (1466973070716)
     *
     * Vars:
     */
    bool TransitionCondition1466973078342::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1466973077670) ENABLED START*/
        return false;
        /*PROTECTED REGION END*/

    }

}
