#ifndef SimpleDropBallCONSTRAINT_H_
#define SimpleDropBall_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* SimpleDropBallCONSTRAINT_H_ */
