#include "Plans/TestPlans/curves1517056420902.h"
using namespace alica;
/*PROTECTED REGION ID(eph1517056420902) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:curves

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1517059003794

     */
    shared_ptr<UtilityFunction> UtilityFunction1517056420902::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1517056420902) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

//State: NewSuccessState in Plan: curves

//State: NewState in Plan: curves

//State: NewState in Plan: curves

}
