#ifndef OppStandardsCONSTRAINT_H_
#define OppStandards_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* OppStandardsCONSTRAINT_H_ */
