#include "Plans/GameStrategy/Other/SimpleDropBall1426696586622.h"
using namespace alica;
/*PROTECTED REGION ID(eph1426696586622) ENABLED START*/ //Add additional using directives here
#include <MSLWorldModel.h>
#include <Game.h>
#include <Ball.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:SimpleDropBall

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1426696586624

     Task: KeepGoal  -> EntryPoint-ID: 1455538209889

     */
    shared_ptr<UtilityFunction> UtilityFunction1426696586622::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1426696586622) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Positioning in Plan: SimpleDropBall

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Situation==start 
     *
     * Plans in State: 				
     *   - Plan - (Name): DropBallPositioning, (PlanID): 1455537014534 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426696586624)
     *   - KeepGoal (1221754402444) (Entrypoint: 1455538209889)
     *
     * States:
     *   - Positioning (1426696586623)
     *   - Execution (1426696626634)
     *   - NewSuccessState (1426696638228)
     *   - DefendGoal (1455538265766)
     *   - Wander (1458562124636)
     *
     * Vars:
     */
    bool TransitionCondition1426696641527::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696640520) ENABLED START*/
        return wm->game->checkSituation(Situation::Start);
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : EgoBall==nullptr 
     *
     * Plans in State: 				
     *   - Plan - (Name): DropBallPositioning, (PlanID): 1455537014534 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426696586624)
     *   - KeepGoal (1221754402444) (Entrypoint: 1455538209889)
     *
     * States:
     *   - Positioning (1426696586623)
     *   - Execution (1426696626634)
     *   - NewSuccessState (1426696638228)
     *   - DefendGoal (1455538265766)
     *   - Wander (1458562124636)
     *
     * Vars:
     */
    bool TransitionCondition1458562142910::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1458562141333) ENABLED START*/
        return wm->ball->getEgoBallPosition() == nullptr;
        /*PROTECTED REGION END*/

    }

    //State: Execution in Plan: SimpleDropBall

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : anychildsuccess 
     *
     * Plans in State: 				
     *   - Plan - (Name): DropBallExecution, (PlanID): 1455537039421 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426696586624)
     *   - KeepGoal (1221754402444) (Entrypoint: 1455538209889)
     *
     * States:
     *   - Positioning (1426696586623)
     *   - Execution (1426696626634)
     *   - NewSuccessState (1426696638228)
     *   - DefendGoal (1455538265766)
     *   - Wander (1458562124636)
     *
     * Vars:
     */
    bool TransitionCondition1426696642635::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1426696641744) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : EgoBall==nullptr 
     *
     * Plans in State: 				
     *   - Plan - (Name): DropBallExecution, (PlanID): 1455537039421 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426696586624)
     *   - KeepGoal (1221754402444) (Entrypoint: 1455538209889)
     *
     * States:
     *   - Positioning (1426696586623)
     *   - Execution (1426696626634)
     *   - NewSuccessState (1426696638228)
     *   - DefendGoal (1455538265766)
     *   - Wander (1458562124636)
     *
     * Vars:
     */
    bool TransitionCondition1458562144595::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1458562143087) ENABLED START*/
        return wm->ball->getEgoBallPosition() == nullptr;
        /*PROTECTED REGION END*/

    }

    //State: NewSuccessState in Plan: SimpleDropBall

    //State: DefendGoal in Plan: SimpleDropBall

    //State: Wander in Plan: SimpleDropBall

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : EgoBall!=nullptr 
     *
     * Plans in State: 				
     *   - Plan - (Name): WanderPlan, (PlanID): 1458553921358 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1426696586624)
     *   - KeepGoal (1221754402444) (Entrypoint: 1455538209889)
     *
     * States:
     *   - Positioning (1426696586623)
     *   - Execution (1426696626634)
     *   - NewSuccessState (1426696638228)
     *   - DefendGoal (1455538265766)
     *   - Wander (1458562124636)
     *
     * Vars:
     */
    bool TransitionCondition1458562147436::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1458562144787) ENABLED START*/
        return wm->ball->getEgoBallPosition() != nullptr;
        /*PROTECTED REGION END*/

    }

}
