#include "Plans/Standards/Own/Corner/constraints/CornerExecBounceShot1459362028865Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1459362028865) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CornerExecBounceShot

/*		
 * Tasks: 
 * - EP:1459362049517 : ExecuteStandard (1439997010902)
 * - EP:1459365320409 : ReceiveStandard (1439997023446)
 * - EP:1459365322922 : Defend (1225115406909)
 *
 * States:
 * - WaitForReceiver (1459362049516)
 * - RealignWall (1459365278157)
 * - Wait (1459365280181)
 * - BouncePassOffRobot (1459365281222)
 * - FinishAlign (1459365282539)
 * - WaitForShotToFinish (1459365284057)
 * - WaitForPass (1459365285847)
 * - DefenderWall (1459365287615)
 * - NewSuccessState (1459365294648)
 * - NewSuccessState (1459365296108)
 * - NewSuccessState (1459365297570)
 *
 * Vars:
 */

// State: WaitForReceiver

// State: WaitForReceiver

// State: RealignWall

// State: RealignWall

// State: Wait

// State: Wait

// State: BouncePassOffRobot

// State: BouncePassOffRobot

// State: FinishAlign

// State: FinishAlign

// State: WaitForShotToFinish

// State: WaitForShotToFinish

// State: WaitForPass

// State: WaitForPass

// State: DefenderWall

// State: DefenderWall

// State: NewSuccessState

// State: NewSuccessState

// State: NewSuccessState

// State: NewSuccessState

// State: NewSuccessState

// State: NewSuccessState

}
