#include "Plans/Standards/Own/Corner/constraints/CornerPosBounceShot1459361999064Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1459361999064) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:CornerPosBounceShot

/*		
 * Tasks: 
 * - EP:1459362020730 : ExecuteStandard (1439997010902)
 * - EP:1459362605142 : ReceiveStandard (1439997023446)
 * - EP:1459362606949 : Defend (1225115406909)
 *
 * States:
 * - AlignPasser (1459362020729)
 * - AlignWall (1459362636939)
 * - DefenderWall (1459362640122)
 *
 * Vars:
 */

// State: AlignPasser

// State: AlignPasser

// State: AlignWall

// State: AlignWall

// State: DefenderWall

// State: DefenderWall

}
