#ifndef CarpetCalibratorCONSTRAINT_H_
#define CarpetCalibrator_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* CarpetCalibratorCONSTRAINT_H_ */
