#include "Plans/Goalie/Test/constraints/GoalieDefault1447254438614Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1447254438614) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:GoalieDefault

/*		
 * Tasks: 
 * - EP:1447254438616 : KeepGoal (1221754402444)
 *
 * States:
 * - DriveToGoal (1447254438615)
 * - WatchBall (1447255061404)
 *
 * Vars:
 */

// State: DriveToGoal

// State: DriveToGoal

// State: WatchBall

// State: WatchBall

}
