#ifndef ShootTwoHoledWallCONSTRAINT_H_
#define ShootTwoHoledWall_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ShootTwoHoledWallCONSTRAINT_H_ */
