#ifndef TwoHoledWallMasterCONSTRAINT_H_
#define TwoHoledWallMasterCONSTRAINT_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TwoHoledWallMasterCONSTRAINT_H_ */
