#ifndef TwoHoledWallAlignCONSTRAINT_H_
#define TwoHoledWallAlign_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TwoHoledWallAlignCONSTRAINT_H_ */
