#ifndef TestDribbleCONSTRAINT_H_
#define TestDribble_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TestDribbleCONSTRAINT_H_ */
